config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :watches do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create, :index, :show]
  end

  get "/my_bookings", to: "bookings#my_bookings"
  get "/my_watches_bookings", to: "bookings#my_watches_bookings"
  get "/my_watches", to: "watches#my_watches"
  get "/accept_booking/:id", to: "bookings#accept", as: :accept_booking
  get "/reject_booking/:id", to: "bookings#reject", as: :reject_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :watch

  validates :start_date, :end_date, presence: true
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :watch
  validates :comment, presence: true, length: { maximum: 255, too_long: "Maximum 255 characters allowed" }
  validates :rating, presence: true, inclusion: { in: 1..5, message: "should be from 1 to 5" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :watches, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, :price, :location, :style, presence: true
  validates :style, inclusion: { in: %w[Dress Diver Pilot Field] }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_style,
    against: [ :name, :style ],
    using: {
      tsearch: { prefix: true }
    }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range.first, to: range.last }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :reject]

  def new
    @booking = Booking.new
    @watch = Watch.find(params[:watch_id])
    authorize(@booking)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @watch = Watch.find(params[:watch_id])
    @booking.watch = @watch
    authorize(@booking)
    if @booking.save
      redirect_to my_bookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def my_bookings
    @bookings_accepted = Booking.where(user: current_user, status: "accepted")
    @bookings_pending = Booking.where(user: current_user, status: "pending")
    @bookings_rejected = Booking.where(user: current_user, status: "rejected")
    authorize(@bookings_accepted)
    authorize(@bookings_pending)
    authorize(@bookings_rejected)
  end

  def accept
    @booking.accepted!
    redirect_to my_watches_bookings_path, notice: ''
  end

  def reject
    @booking.rejected!
    redirect_to my_watches_bookings_path, notice: ''
  end

  def my_watches_bookings
    watches = Watch.where(user: current_user)
    @my_watches_bookings_accepted = []
    @my_watches_bookings_rejected = []
    @my_watches_bookings_pending = []
    unless watches.empty?
      watches.each do |watch|
        watch_bookings = watch.bookings.to_a.flatten
        watch_bookings.each do |watch_booking|
          if watch_booking.accepted?
            @my_watches_bookings_accepted << watch_booking
          elsif watch_booking.rejected?
            @my_watches_bookings_rejected << watch_booking
          else
            @my_watches_bookings_pending << watch_booking
          end
        end
      end
      combined_bookings = @my_watches_bookings_accepted + @my_watches_bookings_rejected + @my_watches_bookings_pending
      combined_watches = combined_bookings.map { |booking| booking.watch }
      @remaining_watches = []
      watches.each { |watch| @remaining_watches << watch unless combined_watches.include?(watch) }
    end
    authorize(Booking.first)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize(@booking)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_watch, only: [:new, :create]

  # def index
  #   @reviews = policy_scope(Review)
  # end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.watch = @watch
    authorize(@review)

    if @review.save
      set_watch_average_rating
      # raise
      redirect_to watch_path(@watch)
    else
      render :new
    end
    # redirect: message to browser, new http request. whereas render: generates html and just sends html back as response.
    # re-render the new view,
    # we have non- conditional redirect
  end

  def set_watch_average_rating
    @watch.avg_rating = @watch.reviews.map(&:rating).sum / @watch.reviews.size
    @watch.save
  end

  private

  def set_watch
    @watch = Watch.find(params[:watch_id])
    authorize(@watch)
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_watch, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @watches = policy_scope(Watch).search_by_name_and_style(params[:query])
    else
      @watches = policy_scope(Watch).order(created_at: :desc)
    end
  end

  def show
    @marker = { lat: @watch.latitude, lng: @watch.longitude }
  end

  def new
    @watch = Watch.new
    authorize(@watch)
  end

  def create
    @watch = Watch.new(watch_params)
    @watch.user = current_user
    authorize(@watch)

    if @watch.save
      redirect_to watch_path(@watch), notice: 'Watch was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @watch.update(watch_params)
      redirect_to @watch, notice: 'Watch was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @watch.destroy
    redirect_to watches_path
  end

  private

  def set_watch
    @watch = Watch.find(params[:id])
    authorize(@watch)
  end

  def watch_params
    params.require(:watch).permit(:id, :name, :style, :location, :price, :img_url, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<h1 class="header-stretch text-center">My accepted bookings</h1>
<div class="card-container">
  <% @bookings_accepted.each do |booking| %>
  <div class="card-product">
    <p id="price">$<%= booking.watch.price %>/day</p>
    <% if booking.watch.img_url != nil %>
      <img src="<%= booking.watch.img_url %>">
    <% else %>
      <%= cl_image_tag booking.watch.photo.key %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= link_to booking.watch.name, watch_path(booking.watch) %></h2>
      <p id="rating">
        <% if booking.watch.avg_rating == 1%>
          ★
        <% elsif booking.watch.avg_rating == 2%>
          ★★
        <% elsif booking.watch.avg_rating == 3%>
          ★★★
        <% elsif booking.watch.avg_rating == 4%>
          ★★★★
        <% elsif booking.watch.avg_rating == 5%>
          ★★★★★
        <% end%>
      </p>
      <p>Belongs to: <%= booking.watch.user.name %></p>
      <p>Watch style: <%= booking.watch.style %></p>
      <p>Location: <%= booking.watch.location %></p>
      <p>Booked: <%= booking.start_date %> to <%= booking.end_date %></p>
      <% unless policy(booking.watch).owner? %>
        <p id="review"><%= link_to "Review this watch", new_watch_review_path(booking.watch), class: "btn btn-light btn-sm" %></p>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<h1 class="header-stretch text-center">My pending bookings</h1>
<div class="card-container">
  <% @bookings_pending.each do |booking| %>
  <div class="card-product">
    <p id="price">$<%= booking.watch.price %>/day</p>
    <% if booking.watch.img_url != nil %>
      <img src="<%= booking.watch.img_url %>">
    <% else %>
      <%= cl_image_tag booking.watch.photo.key %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= link_to booking.watch.name, watch_path(booking.watch) %></h2>
      <p id="rating">
        <% if booking.watch.avg_rating == 1%>
          ★
        <% elsif booking.watch.avg_rating == 2%>
          ★★
        <% elsif booking.watch.avg_rating == 3%>
          ★★★
        <% elsif booking.watch.avg_rating == 4%>
          ★★★★
        <% elsif booking.watch.avg_rating == 5%>
          ★★★★★
        <% end%>
      </p>
      <p>Belongs to: <%= booking.watch.user.name %></p>
      <p>Watch style: <%= booking.watch.style %></p>
      <p>Location: <%= booking.watch.location %></p>
      <p>Requested: <%= booking.start_date %> to <%= booking.end_date %></p>
    </div>
  </div>
  <% end %>
</div>

<h1 class="header-stretch text-center">My rejected bookings</h1>
<div class="card-container my-rejected-bookings-container">
  <% @bookings_rejected.each do |booking| %>
  <div class="card-product">
    <p id="price">$<%= booking.watch.price %>/day</p>
    <% if booking.watch.img_url != nil %>
      <img src="<%= booking.watch.img_url %>">
    <% else %>
      <%= cl_image_tag booking.watch.photo.key %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= link_to booking.watch.name, watch_path(booking.watch) %></h2>
      <p id="rating">
        <% if booking.watch.avg_rating == 1%>
          ★
        <% elsif booking.watch.avg_rating == 2%>
          ★★
        <% elsif booking.watch.avg_rating == 3%>
          ★★★
        <% elsif booking.watch.avg_rating == 4%>
          ★★★★
        <% elsif booking.watch.avg_rating == 5%>
          ★★★★★
        <% end%>
      </p>
      <p>Belongs to: <%= booking.watch.user.name %></p>
      <p>Watch style: <%= booking.watch.style %></p>
      <p>Location: <%= booking.watch.location %></p>
      <p>Requested: <%= booking.start_date %> to <%= booking.end_date %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/my_watches_bookings.html.erb
<h1 class="header-stretch text-center">My accepted bookings</h1>
<div class="card-container">
  <% @my_watches_bookings_accepted.each do |booking|%>
    <div class="card-product">
      <p id="price">$<%= booking.watch.price %>/day</p>
      <% if booking.watch.img_url != nil %>
        <img src="<%= booking.watch.img_url %>">
      <% else %>
        <%= cl_image_tag booking.watch.photo.key %>
      <% end %>
      <div class="card-product-infos">
        <h2><%= link_to booking.watch.name, watch_path(booking.watch) %></h2>
        <p id="rating">
        <% if booking.watch.avg_rating == 1%>
          ★
        <% elsif booking.watch.avg_rating == 2%>
          ★★
        <% elsif booking.watch.avg_rating == 3%>
          ★★★
        <% elsif booking.watch.avg_rating == 4%>
          ★★★★
        <% elsif booking.watch.avg_rating == 5%>
          ★★★★★
        <% end%>
        </p>
        <p>Requested by: <%= booking.user.name %></p>
        <p>Watch style: <%= booking.watch.style %></p>
        <p>Location: <%= booking.watch.location %></p>
        <p>Booked: <%= booking.start_date %> to <%= booking.end_date %></p>
      </div>
    </div>
  <% end %>
</div>

<h1 class="header-stretch text-center">My pending bookings</h1>
<div class="card-container">
  <% @my_watches_bookings_pending.each do |booking| %>
    <div class="card-product">
      <p id="price">$<%= booking.watch.price %>/day</p>
      <% if booking.watch.img_url != nil %>
        <img src="<%= booking.watch.img_url %>">
      <% else %>
        <%= cl_image_tag booking.watch.photo.key %>
      <% end %>
      <div class="card-product-infos">
        <h2><%= link_to booking.watch.name, watch_path(booking.watch) %></h2>
        <p id="rating">
        <% if booking.watch.avg_rating == 1%>
          ★
        <% elsif booking.watch.avg_rating == 2%>
          ★★
        <% elsif booking.watch.avg_rating == 3%>
          ★★★
        <% elsif booking.watch.avg_rating == 4%>
          ★★★★
        <% elsif booking.watch.avg_rating == 5%>
          ★★★★★
        <% end%>
        </p>
        <p>Requested by: <%= booking.user.name %></p>
        <p>Watch style: <%= booking.watch.style %></p>
        <p>Location: <%= booking.watch.location %></p>
        <p>Requested: <%= booking.start_date %> to <%= booking.end_date %></p>
        <p> <%= link_to 'Accept', accept_booking_path(booking), class: "btn btn-secondary btn-sm mr-2" %>
        <%= link_to 'Reject', reject_booking_path(booking), class: "btn btn-warning btn-sm" %></p>
      </div>
    </div>
  <% end %>
</div>

<h1 class="header-stretch text-center">My vacant listings</h1>
<div class="card-container my-rejected-bookings-container">
  <% if @remaining_watches.nil? %>
    <p>No Watches to display</p>
  <% else %>
    <% @remaining_watches.each do |watch|%>
      <div class="card-product">
        <p id="price">$<%= watch.price %>/day</p>
        <% if watch.img_url != nil %>
          <img src="<%= watch.img_url %>">
        <% else %>
          <%= cl_image_tag watch.photo.key %>
        <% end %>
        <div class="card-product-infos">
          <h2><%= link_to watch.name, watch_path(watch) %></h2>
           <p id="rating">
        <% if watch.avg_rating == 1%>
          ★
        <% elsif watch.avg_rating == 2%>
          ★★
        <% elsif watch.avg_rating == 3%>
          ★★★
        <% elsif watch.avg_rating == 4%>
          ★★★★
        <% elsif watch.avg_rating == 5%>
          ★★★★★
        <% end%>
        </p>
          <p>Watch style: <%= watch.style %></p>
          <p>Location: <%= watch.location %></p>
      </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<p id="widget" data-unavailable="<%= @watch.unavailable_dates.to_json %>"></p>

<div class="form-wrapper">
  <%= simple_form_for([@watch, @booking]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watchbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="">
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>

</html>

app/views/pages/home.html.erb
<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://qph.fs.quoracdn.net/main-qimg-ff3264c29718171aa6ac08bd429f4643-c"> %>
<div class="home-video-wrapper">
  <%= video_tag "video.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
  <div class="homepage-content">
    <h1 class="homepage-h1">WatchBnB</h1>
    <div class="container call-to-action">
      <div class="single-call-to-action">
        <p>Can't afford to buy a nice watch?</p>
        <p>RENT one now!</p>
        <div class="button-container">
          <%= link_to "Rent now", watches_path, class: "btn btn-danger" %>
        </div>
      </div>

      <div class="single-call-to-action">
        <p>Got watches and want money?</p>
        <p>LIST yours now!</p>
        <div class="button-container">
          <%= link_to "List now", new_watch_path, class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [ @watch, @review ] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :comment %>
  <%= f.input :rating %>

  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= review.comment %>
      <br>
      <%= review.rating %>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= render "form" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible mb-5" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible mb-5" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Watchbnb Inc.</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://media.istockphoto.com/vectors/watch-flat-design-switzerland-icon-vector-id1018493446?k=20&m=1018493446&s=170667a&w=0&h=nwHRqaan9TxPrHSx1IRQeSCwXGOIrsMcqsyf9uXaSqE=
" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Browse Watches", watches_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://i.pinimg.com/736x/3f/94/70/3f9470b34a8e3f526dbdb022f9f19cf7.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "My Watches", my_watches_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/watches/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
    <div class="simple-form">
      <%= simple_form_for(@watch) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.input :name %>
        <%= f.input :style, label: 'Style', collection: %w[Dress Diver Pilot Field]%>
        <%= f.input :location %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
       <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/watches/edit.html.erb
<h1 class="header-stretch text-center"> Edit <%= @watch.name %> </h1>

<%= render "form" %>

app/views/watches/index.html.erb
<div class="search-area">
  <%= form_tag watches_path, method: :get do %>
  <div class="d-flex justify-content-between">
    <%= text_field_tag :query,
    params[:query],
    class: "search-form-control",
    placeholder: "Find a watch"
    %>
    <%= submit_tag "Search", class: "btn btn-primary btn-lg search-box" %>
  </div>
  <div class="list-watch-button">
    <%= link_to "List New Watch", new_watch_path, class: "btn btn-secondary btn-lg list-watch mt-40" %>
  </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
</div>

<h1 class="header-stretch text-center"> Local listings </h1>

<div class="card-container">
  <% @watches.each do |watch| %>
  <div class="card-product">
    <p id="price">$<%= watch.price %>/day</p>
    <% if watch.img_url != nil %>
      <img src="<%= watch.img_url %>">
    <% else %>
      <%= cl_image_tag watch.photo.key %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= link_to watch.name, watch_path(watch) %></h2>
      <p id="rating">
        <% if watch.avg_rating == 1%>
          ★
        <% elsif watch.avg_rating == 2%>
          ★★
        <% elsif watch.avg_rating == 3%>
          ★★★
        <% elsif watch.avg_rating == 4%>
          ★★★★
        <% elsif watch.avg_rating == 5%>
          ★★★★★
        <% end%>
      </p>
      <p>Owner:
        <% if watch.user == current_user  %>
          <b><i><%= "You" %></i></b>
        <% else %>
          <%= watch.user.name %>
        <% end %>
      </p>
      <p>Watch style: <%= watch.style %></p>
      <p>Location: <%= watch.location %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/watches/my_watches.html.erb
<% @my_watches.each do |watch| %>
<div class="cards">
  <img src="<%= watch.img_url %>">
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to watch.name, watch_path(watch) %></h2>
      <p><%= watch.style %></p>
      <p><%= watch.location %></p>
    </div>
    <h2 class="card-trip-pricing">$<%= watch.price %>/day</h2>
  </div>
</div>
<% end %>

app/views/watches/new.html.erb
<h1 class="header-stretch text-center"> List your watch now! </h1>
<br>
<%= render "form" %>

app/views/watches/show.html.erb
<h1 class="header-stretch text-center"> Watch overview </h1>

<div class="container-watchshow">
  <div class="watch-image">
    <% if @watch.img_url != nil %>
      <img src="<%= @watch.img_url %>" width=400 height=400>
    <% else %>
      <%= cl_image_tag @watch.photo.key, height: 400, width: 400, crop: :fill %>
    <% end %>
  </div>

  <div class="d-flex flex-column align-items-center">
    <h2><%= @watch.name %></h2>
    <p class="mt-3"> Owner:
      <% if @watch.user == current_user  %>
        <b><i><%= "You" %></i></b>
      <% else %>
        <%= @watch.user.name %>
      <% end %>
    </p>
    <p> Style: <%= @watch.style %> </p>
    <p> Location: <%= @watch.location %> </p>
    <p> Price per day: $<%= @watch.price %> </p>
    <%# <img href="<% @watch.img_url"/> %>
    <p> Reviews: </p>
    <div class="review-container">
      <% @watch.reviews.each do |review| %>
        <div class="review-bubble">
          "<%= review.comment%>"
          <div class="review-text">
            <%= review.rating%> stars
          </div>
        </div>
        <%end%>
    </div>

    <% if policy(@watch).edit? %>
    <p><%= link_to 'Edit', edit_watch_path(@watch) %></p>
    <% end %>

    <% unless policy(@watch).owner? %>
      <%# don't forget to update watches_path %>
      <p><%= link_to "Rent Now", new_watch_booking_path(@watch), class: "btn btn-danger mt-3" %></p>
    <% end %>

    <% if policy(@watch).destroy? %>
      <p><%= link_to 'Delete', watch_path(@watch), method: :delete %></p>
    <% end %>
  </div>

  <div id="map"
    style="width: 400px; height: 400px;"
    data-marker="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>